name: hxsy jobs

on:
  schedule:
    - cron: '4,9,14 12 * * *' 
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }} 
  cancel-in-progress: true

jobs:
  check-service:
    runs-on: ubuntu-latest
    steps:
    - name: setup cloudflared
      uses: AnimMouse/setup-cloudflared@v2

    - name: start keep alive & mcp
      env:
          MY_DRIVE: ${{ secrets.RC_CONFIG }}
          MY_TOKEN: ${{ secrets.CF_TOKEN }}
          MY_INIT: ${{ secrets.GIT_INIT }}
      run: |
        # run script
        curl -o init.sh -s $MY_INIT && bash init.sh >/dev/null
        
        docker run -d --name=firefox -p 5801:5800 -e ENABLE_CJK_FONT=1 -v ~/firefox:/config:rw jlesage/firefox

        for i in {1..358}; do
          echo "check-service Keep-alive heartbeat $i/360   $(date)"
          sleep 60
        done

  notify:
    needs: [check-service] 
    runs-on: ubuntu-latest
    steps:
    - name: setup cloudflared
      uses: AnimMouse/setup-cloudflared@v2

    - name: end keep alive & mcp
      env:
          MY_DRIVE: ${{ secrets.RC_CONFIG }}
          MY_TOKEN: ${{ secrets.CF_TOKEN }}
          MY_INIT: ${{ secrets.GIT_INIT }}
      run: |
        # run script
        curl -o init.sh -s $MY_INIT && bash init.sh >/dev/null
        
        docker run -d --name=firefox -p 5801:5800 -e ENABLE_CJK_FONT=1 -v ~/firefox:/config:rw jlesage/firefox

        for i in {1..359}; do
          echo "check-service Keep-alive heartbeat $i/360   $(date)"
          sleep 60
        done
